source 'https://rubygems.org'

gem 'bunny', '~> 2.3.1'
gem 'bunny_burrow', '~> 0.1.0'
gem 'env_hash_config', '~> 1.0.0'
gem 'sentry-raven', '~> 1.0.0'

group :development, :test do
  gem 'pry'
  gem 'pry-nav'
end

group :test do
  gem 'rspec', '~> 3.0'
  gem 'rspec-its', '~> 1.2.0'
  gem 'simplecov', '~> 0.11.2'
  gem 'simplecov-rcov', '~> 0.2.3'
end


