source 'https://rubygems.org'

gem 'bunny', '~> 2.4'
gem 'bunny_burrow', '~> 1.4'
gem 'env_hash_config', '~> 1.1'
gem 'sentry-raven', '~> 1.1'

group :development, :test do
  gem 'pry'
  gem 'pry-nav'
end

group :test do
  gem 'rspec', '~> 3.0'
  gem 'rspec-its', '~> 1.2'
  gem 'simplecov', '~> 0.11'
  gem 'simplecov-rcov', '~> 0.2'
end


